#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:assert", "assert")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:data", "data")
#@ if data.values.COMPLIANCE == "cis":
#@overlay/match missing_ok=True,by=overlay.subset({"kind":"KubeadmControlPlane"})
---
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
         extraArgs:
          #@overlay/match missing_ok=True
          auto-tls: "false"
#@ end