#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ if data.values.COMPLIANCE == "stig":
#@overlay/match missing_ok=True,by=overlay.subset({"kind":"KubeadmControlPlane"})
---
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      etcd:
        local:
         extraArgs:
          #@overlay/match missing_ok=True
          peer-auto-tls: "false"
#@ end